FROM python:3.7.3-stretch

RUN apt-get update && apt-get install -y patchelf
RUN pip install https://download.pytorch.org/whl/cu100/torch-1.1.0-cp37-cp37m-linux_x86_64.whl numpy

RUN mkdir /optorch
WORKDIR /optorch

ARG VERSION
COPY dist/optorch-${VERSION}-cp37-cp37m-manylinux1_x86_64.whl .
RUN pip install optorch-${VERSION}-cp37-cp37m-manylinux1_x86_64.whl
RUN pip install matplotlib

COPY examples/rosenbrock.py .
COPY examples/circle_fit.py .
RUN mkdir -p results

CMD ["python3.7", "rosenbrock.py"]
